language: python
python:
  - "3.6"
  - "3.7"

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

before_script:
  - sudo -u postgres createuser admin
  - sudo -u postgres createdb test
  - python manager.py db init
  - python manager.py db migrate
  - python manager.py db upgrade

# command to run tests
script:
    - nosetests --with-coverage --cover-package=api
after_success:
  coveralls